version: '3.8'
services:
  appseed-app:
    container_name: Appseed-app
    restart: always
    env_file: .env
 
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
       - "5000:5000"
    networks:
      - weblyticHome 
    

networks:
  weblyticHome:
    driver: bridge


 